spring:
  application:
    name: auth
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: pet
    password: Khoa2001
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
server:
  servlet:
    context-path: /auth
logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  time-expired: 18000
  private-key: Pre-authenticated entry point called. Rejecting access